version: '2'

services:
  demoweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  fulldemoweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  demowebsite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  cinema.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  evol.cinema.website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
